<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE breakfast_menu [
  <!ELEMENT breakfast_menu (food+)>
  <!ELEMENT food (name,price,description,calories?)>  
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT calories (#PCDATA)>
  <!ENTITY en "Bread">
  <!ATTLIST food id CDATA "01">
  <!ATTLIST food type CDATA "fast">
  ]>
<breakfast_menu>
	<food id="01" >
		<name>&en;</name>
		<price>$5.95</price
		><description>two of our famous Belgian Waffles with plenty of real maple syrup</description>
	</food>
	<food>
		<name>Strawberry Belgian Waffles</name>
		<price>$7.95</price>
		<description>light Belgian waffles covered with strawberries and whipped cream</description>
		<calories>900</calories>
	</food>

	<food>
		<name>Berry-Berry Belgian Waffles</name>
		<price>$8.95</price>
		<description>light Belgian waffles covered with an assortment of fresh berries and whipped cream</description>
		<calories>900</calories>
	</food>
	<food>

		<name>French Toast</name>
		<price>$4.50</price>
		<description>thick slices made from our homemade sourdough bread</description>
		<calories>600</calories>
	</food>
	<food>
		<name>Homestyle Breakfast</name>

		<price>$6.95</price>
		<description>two eggs, bacon or sausage, toast, and our ever-popular hash browns</description>
		<calories>950</calories>
	</food>
</breakfast_menu>


