=== quoc2002/fptaptech/sem2/MLJ/XML vs JDBC/src/Examples/Session02/Module 3 _ 4/census_record.dtd
<!ELEMENT census-record (date, address, person+)>
<!ATTLIST census-record taker CDATA #REQUIRED>
<!ENTITY add "Hanoi">
<!ENTITY add1  SYSTEM "hn.txt">

<!-- date the info was collected -->
<!ELEMENT date (year, month, day)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ATTLIST date  language CDATA #FIXED "vn">

<!-- address information -->
<!ELEMENT address (street, city, county, country, postalcode)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT county (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postalcode (#PCDATA)>

<!-- person information -->
<!ELEMENT person (name, age, gender)>
<!ELEMENT name (first, last, (junior | senior)?)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT junior EMPTY>
<!ELEMENT senior EMPTY>
<!ATTLIST person  pid     ID                   #REQUIRED>
<!ATTLIST person  employed  (fulltime|parttime)  #IMPLIED>

=== quoc2002/fptaptech/sem2/MLJ/XML vs JDBC/out/production/XML vs JDBC/Examples/Session02/Module 3 _ 4/census_record.xml
<?xml version="1.0"?>
<!DOCTYPE census-record SYSTEM "census_record.dtd">
<census-record taker="3163">
  <date language="vn">
  	<year>2003</year>
	<month>10</month>
	<day>11</day>
  </date>
  <address>
    <street>471 Skipstone Lane </street>
    <city></city>
    <county>Greenhill</county>
    <country>Oz</country>
    <postalcode>885JKL</postalcode>
  </address>
  <person employed="fulltime" pid="P270405">
    <name>
      <first>Meeble</first>
      <last>Bigbug</last>
      <junior/>
    </name>
    <age>39</age>
    <gender>male</gender>
  </person>
  <person employed="parttime" pid="P273882">
    <name>
      <first>Mable</first>
      <last>Bigbug</last>
	  <senior/>
    </name>
    <age>36</age>
    <gender>female</gender>
  </person>
  <person pid="P472891">
    <name>
      <first>Marble</first>
      <last>Bigbug</last>
    </name>
    <age>11</age>
    <gender>male</gender>
  </person>
</census-record>
